### ISSUE TITLE
api reports doorstatus as unknown

### ISSUE THREAD

**Issue by jnweiger** [fablabnbg/FLNdoors_server#3]
http://api.fablab-nuernberg.de/tuer.php is broken. Please give hints how to fix.

**Comment by pathim** [comment]
Status sending is done by app_status.send_status.
This is called by app_request.log_success.
Also heartbeat.py sends the status.
heartbeat.py has to be run regularly. I think at least once per 15min.
Maybe some cronjob for the heartbeat has been removed.

**Comment by faheus** [comment]
i don't have access to the system.

**Comment by jnweiger** [comment]
Die Übertragung des Status funktioniert nicht, wenn die Uhr des Türservers falsch geht.
Aus nicht bekannten Gründen ging die Uhr mindestens einmal falsch.
Es wurde die lokale Zeit als UTC Zeit angezeigt.
Es ist bisher nicht geklärt ob diese falsche Zeit durch ntp synchronisation entstanden ist.
Falls als der Türstatus wieder nicht funktioniert:

  date -u -s "Nov 26 19:13:51 UTC 2016"

Natürlich mit richtigem Datum und Zeit
