### ISSUE TITLE
infobeamer gets some dates wrong by 1h(but not all)

### ISSUE THREAD

**Issue by jnweiger** [fablabnbg/FLNdoors_server#5]
![20161203_005609](https://cloud.githubusercontent.com/assets/1108546/20860645/46c055a2-b97d-11e6-8ab4-7c3966723caf.jpg)

Openlab, chaostreff, and kidslab are imported from the calender with correct start time.
Workshops OpenWordclock, (and also Inkscape Yesterday, not shown in the screenshot) were off by one hour. they start at 19h, but show 18h here.

Repair Cafe shows the correct time 14h, but the wrong date. 

Is there a way to manually edit what was imported?

**Comment by IVI053** [comment]
Nothing todo with this repo
